version = 1
SPDX-PackageName = "glim"
SPDX-PackageSupplier = "dhan <sr.dhanesh@protonmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/dhanquna/glim"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 dhan <sr.dhanesh@protonmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "icons-original/invader/neon.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 KDE neon <https://neon.kde.org>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
